### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/Insight#1]
Free to change Background color, font family,text-color etc

**Comment by parthib2004** [comment]
Please assign this to me!

**Comment by Swadeeppatil** [comment]
hello 
plz assign me this task
@harshit1142

**Comment by harshit1142** [comment]
@parthib2004 you are assigned to this. Do star ⭐ the repo and follow me to start.

**Comment by harshit1142** [comment]
@Swadeeppatil if you can find something creative to modify do create a new issue

**Comment by Swadeeppatil** [comment]
@harshit1142  ok
