### ISSUE TITLE
Adjust UI for the landing page 

### ISSUE THREAD

**Issue by Dipeshdahiya** [harshit1142/Insight#3]
Hi i will improve the css design , and readjust your whole page please assign this issue to me

**Comment by harshit1142** [comment]
@Dipeshdahiya Sure, Do star ⭐ the repo and follow me to start.

**Comment by hemanthhhhhh** [comment]
can I contribute to this

**Comment by harshit1142** [comment]
@hemanthhhhhh someone is already assigned.

**Comment by Dipeshdahiya** [comment]
@harshit1142 i already stared the repo

**Comment by harshit1142** [comment]
Yes, this issue is fixed now.
